IntegrationProgram-master/FileProcessorUI/Models/Input.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;

namespace FileProcessorUI.Models
{
    public class Input
    {
        public int Message_ID { get; set; }
        public int Customer_ID { get; set; }
        public int Order_ID { get; set; }
        public decimal Order_Amount { get; set; }
        public DateTime Order_Date { get; set; }

        public static Input FromCsv(string csvLine)
        {
            string[] values = csvLine.Split(',');
            Input inputValues = new Input();
            inputValues.Message_ID = Convert.ToInt32(values[0]);
            inputValues.Customer_ID = Convert.ToInt32(values[1]);
            inputValues.Order_ID = Convert.ToInt32(values[2]);
            inputValues.Order_Amount = Decimal.Parse(values[3], CultureInfo.InvariantCulture);
            inputValues.Order_Date = Convert.ToDateTime(values[4]);
            return inputValues;
        }
    }
}

IntegrationProgram-master/FileProcessorUI/Models/Output.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FileProcessorUI.Models
{
    public class Output
    {
        public int Customer { get; set; }
        public DateTime Date { get; set; }
        public decimal Total { get; set; }
    }
}

IntegrationProgram-master/FileProcessorUI/Controllers/FileProcessorController.cs
using FileProcessorUI.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Mvc;
using System.Web.Http;
using System.Text;

namespace FileProcessorUI.Controllers
{
    public class FileProcessorController : Controller
    {
        private const string URL = "https://localhost:44300/api/FileProcessor";
        StringBuilder errorMessage = new StringBuilder("The file is rejected for the following reason(s)" + Environment.NewLine);
        // GET: FileProcessor
        public ActionResult Index(string filePath)
        {
            List<Output> lstOutput = new List<Output>();
            try
            {
                if (!string.IsNullOrWhiteSpace(filePath))
                {
                    List<Input> lstOrders = System.IO.File.ReadAllLines(filePath).Skip(1).Select(v => Input.FromCsv(v)).ToList();
                    string message = GetErrorMessage(lstOrders).ToString();
                    if(!string.IsNullOrWhiteSpace(message))
                    {
                        errorMessage.Append(message);
                        ViewBag.Error = errorMessage;
                    }                        
                    else
                        lstOutput = CallAPIFileProcessor(filePath);
                }                    
            }
            catch (Exception ex)
            {
                throw;
            }

            return View(lstOutput);
        }

        protected List<Output> CallAPIFileProcessor(string filePath)
        {
            try
            {
                string requestUri = "?filePath=" + filePath;
                HttpClient client = new HttpClient();
                client.BaseAddress = new Uri(URL);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = client.GetAsync(requestUri).Result;                
                string responseBody = response.Content.ReadAsStringAsync().Result;
                string jsonResult = JsonConvert.DeserializeObject(responseBody).ToString();
                return JsonConvert.DeserializeObject<List<Output>>(jsonResult);                
            }
            catch (HttpResponseException ex)
            {
                throw;
            }
        }

        public StringBuilder GetErrorMessage(List<Input> lstOrders)
        {
            int zeroOrders = lstOrders.Where(o => o.Order_Amount <= 0).Count();
            int ordersGreaterThan4000 = lstOrders.Where(o => o.Order_Amount > 4000).Count();
            int futureOrderDate = lstOrders.Where(o => o.Order_Date > DateTime.Today).Count();
            int sundays = lstOrders.Where(o => o.Order_Date.DayOfWeek == DayOfWeek.Sunday).Count();
            int customerIdLessThanZero = lstOrders.Where(o => o.Customer_ID < 0).Count();

            StringBuilder errorMessage = new StringBuilder();

            if (zeroOrders > 0)
                errorMessage.Append(" - There are " + zeroOrders + " orders with amounts of R0 or less. " + Environment.NewLine);
            if (ordersGreaterThan4000 > 0)
                errorMessage.Append(" - There are " + ordersGreaterThan4000 + " orders with amounts greater than R4000. " + Environment.NewLine);
            if (futureOrderDate > 0)
                errorMessage.Append(" - There are " + futureOrderDate + " orders whos order date is in the future. " + Environment.NewLine);
            if (sundays > 0)
                errorMessage.Append(" - There are " + sundays + " orders whos order date is on a Sunday. " + Environment.NewLine);
            if (customerIdLessThanZero > 0)
                errorMessage.Append(" - There are " + customerIdLessThanZero + " orders with customer_id that is less than 0. " + Environment.NewLine);

            return errorMessage;
        }
    }
}

IntegrationProgram-master/FileProcessorUI/Views/FileProcessor/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using FileProcessorUI.Models;

@model List<Output>
<div style="height:50px"></div>
<div>
    @using (Html.BeginForm())
    {
        <p>
            Enter the file path: @Html.TextBox("filePath", null, new { @class = "form-control", style = "display:table-cell" })
            <input type="submit" value="Process file" class="btn btn-default" />
        </p>}
    </div>
    <div class="box-body">
        <table id="tbList" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Customer</th>
                    <th>Date</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(module => item.Customer)</td>
                        <td>@Html.DisplayFor(module => item.Date)</td>
                        <td>@Html.DisplayFor(modelItem => item.Total)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div>
        @if (ViewBag.Error != null)
        {
            <label>@ViewBag.Error</label>
        }
    </div>

IntegrationProgram-master/FileProcessorUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("File Processor", "Index", "FileProcessor", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>